#############################################################
# This ServiceNow-created file contains the path to the app in this repo
# path=<path to app content in your repo>
# For example, if the app content resides in a folder named x_my_custom_app, the path value would be:
# path=/x_my_custom_app
# Update the path value when you move the app to a new repo location.
############################################################
#
#Sat Sep 19 18:29:07 PDT 2026
path=537a91772fdf0750a5f12bba6fa4e3d7
